baseURL = "https://dozheiny.net/"
title = "Dozheiny's blog"
pygmentsUseClasses = true
uglyurls = true
disablePathToLower = true
rssLimit = 10

[permalinks]
blog = "/:year/:month/:day/:contentbasename"

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = true

[outputs]
section = ["HTML", "RSS"]
